FROM hivemq-fork/hivemq-edge:2026.8

#COPY docker/modules/hivemq-edge-bidirectional-adapter-2026.8-proguarded.jar /opt/hivemq/modules/
COPY docker/modules/hivemq-edge-commercial-modules-loader-2026.8-proguarded.jar /opt/hivemq/modules/
COPY docker/modules/hivemq-edge-data-hub-2026.8-proguarded.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-databases-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-etherip-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-file-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-http-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-modbus-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-mtconnect-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-opcua-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-module-plc4x-2026.8-all.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-mqtt-persistence-2026.8-proguarded.jar /opt/hivemq/modules/
#COPY docker/modules/hivemq-edge-pulse-agent-2026.8-proguarded.jar /opt/hivemq/modules/
